# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class Amount(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, amount: float=None):  # noqa: E501
        """Amount - a model defined in Swagger

        :param amount: The amount of this Amount.  # noqa: E501
        :type amount: float
        """
        self.swagger_types = {
            'amount': float
        }

        self.attribute_map = {
            'amount': 'amount'
        }
        self._amount = amount

    @classmethod
    def from_dict(cls, dikt) -> 'Amount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Amount of this Amount.  # noqa: E501
        :rtype: Amount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> float:
        """Gets the amount of this Amount.

        Positive number to deposit and negative number to withdraw  # noqa: E501

        :return: The amount of this Amount.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount: float):
        """Sets the amount of this Amount.

        Positive number to deposit and negative number to withdraw  # noqa: E501

        :param amount: The amount of this Amount.
        :type amount: float
        """

        self._amount = amount
